### ISSUE TITLE
NullPointerException thrown for some articles

### ISSUE THREAD

**Issue by maxxkia** [CeON/CERMINE#52]
Hi,
When I tried to parse the following documents
- http://www.lrec-conf.org/proceedings/lrec2014/pdf/14_Paper.pdf
- http://nbn-resolving.de/urn:nbn:de:0168-ssoar-424669
- http://nbn-resolving.de/urn:nbn:de:0168-ssoar-457680
- http://www.lrec-conf.org/proceedings/lrec2016/pdf/71_Paper.pdf
- http://www.lrec-conf.org/proceedings/lrec2016/pdf/86_Paper.pdf

With the following piece of code:
```
Element result = extractor.getContentAsNLM();
```

I get the following exception
```
Exception in thread "main" java.lang.NullPointerException
	at pl.edu.icm.cermine.metadata.transformers.MetadataToNLMConverter.convertJournalMetadata(MetadataToNLMConverter.java:61)
	at pl.edu.icm.cermine.metadata.transformers.MetadataToNLMConverter.convert(MetadataToNLMConverter.java:42)
	at pl.edu.icm.cermine.InternalContentExtractor.getMetadataAsNLM(InternalContentExtractor.java:198)
	at pl.edu.icm.cermine.InternalContentExtractor.getContentAsNLM(InternalContentExtractor.java:303)
	at pl.edu.icm.cermine.ContentExtractor.getContentAsNLM(ContentExtractor.java:662)
	at pl.edu.icm.cermine.ContentExtractor.getContentAsNLM(ContentExtractor.java:678)
```

**Comment by maxxkia** [comment]
I tried to get around this problem by just parsing the body and references section:
```
Element body = extractor.getBodyAsNLM();
List<Element> references = extractor.getReferencesAsNLM();
```

but again some other problem occurs when parsing the references section:
```
Exception in thread "main" java.lang.NullPointerException
	at pl.edu.icm.cermine.InternalContentExtractor.getReferencesAsNLM(InternalContentExtractor.java:225)
	at pl.edu.icm.cermine.ContentExtractor.getReferencesAsNLM(ContentExtractor.java:444)
	at pl.edu.icm.cermine.ContentExtractor.getReferencesAsNLM(ContentExtractor.java:460)
```

**Comment by dtkaczyk** [comment]
@maxxkia Thanks for reporting. Unfortunately, I wasn't able to reproduce this on my laptop so far. Could you specify which CERMINE and Java version you use? Also, please provide exact code you are using, starting from reading in the PDF files.

**Comment by maxxkia** [comment]
I'm using CERMINE 1.13, and running Java 1.8.0_131.

Ok, after some debugging I figured out where the problem was. In my older code I was instantiating the extractor once:
```
ContentExtractor extractor = new ContentExtractor();
```

And then processed the documents in a loop
```
for (InputStream is : inputStreams)
{
	extractor.setPDF(is);
	Element body = extractor.getContentAsNLM();
}
``` 

Then, changing the code as follows fixed the problem:
```
for (InputStream is : inputStreams)
{
	ContentExtractor extractor = new ContentExtractor();
	extractor.setPDF(is);
	Element body = extractor.getContentAsNLM();
}
``` 

So actually something is going wrong in `setPDF` since it looks like it's not initializing properly after a document has been processed. Or am I using it in a wrong way?

**Comment by dtkaczyk** [comment]
No, you are right, it was a bug. I believe it is fixed by commit https://github.com/CeON/CERMINE/commit/82c28dcfde734a634429701d52baa29a3728c480 Could you take a look at the newest code in master branch and test it in your setting?

**Comment by maxxkia** [comment]
Yes, the problem is solved now. Thanks.
