### ISSUE TITLE
AssertionError in ContentExtractor().getContentAsNLM()

### ISSUE THREAD

**Issue by maxxkia** [CeON/CERMINE#53]
When attempting to extract data from this article https://doi.org/10.7717/peerj-cs.118 (and probably any other article with the same PDF layout) the following failure occurs:
```
java.lang.AssertionError
	at pl.edu.icm.cermine.structure.readingorder.DocumentPlane.add(DocumentPlane.java:165)
	at pl.edu.icm.cermine.structure.readingorder.DocumentPlane.<init>(DocumentPlane.java:95)
	at pl.edu.icm.cermine.structure.HierarchicalReadingOrderResolver.groupZonesHierarchically(HierarchicalReadingOrderResolver.java:207)
	at pl.edu.icm.cermine.structure.HierarchicalReadingOrderResolver.reorderZones(HierarchicalReadingOrderResolver.java:122)
	at pl.edu.icm.cermine.structure.HierarchicalReadingOrderResolver.resolve(HierarchicalReadingOrderResolver.java:96)
	at pl.edu.icm.cermine.ExtractionUtils.resolveReadingOrder(ExtractionUtils.java:79)
	at pl.edu.icm.cermine.InternalContentExtractor.doWork(InternalContentExtractor.java:354)
	at pl.edu.icm.cermine.InternalContentExtractor.doWork(InternalContentExtractor.java:341)
	at pl.edu.icm.cermine.InternalContentExtractor.doWork(InternalContentExtractor.java:341)
	at pl.edu.icm.cermine.InternalContentExtractor.doWork(InternalContentExtractor.java:341)
	at pl.edu.icm.cermine.InternalContentExtractor.doWork(InternalContentExtractor.java:341)
	at pl.edu.icm.cermine.InternalContentExtractor.getContentAsNLM(InternalContentExtractor.java:301)
	at pl.edu.icm.cermine.ContentExtractor.getContentAsNLM(ContentExtractor.java:662)
	at pl.edu.icm.cermine.ContentExtractor.getContentAsNLM(ContentExtractor.java:678)
	at pl.edu.icm.cermine.ContentExtractorLoopTest.extractionLoopTest(ContentExtractorLoopTest.java:57)
```

**Comment by maxxkia** [comment]
You can easily test this by adding this document to `ContentExtractorLoopTest` class.

**Comment by dtkaczyk** [comment]
It should be fixed by commit https://github.com/CeON/CERMINE/commit/93c0603b52ca4441f0d674152919e134d0f99a26 - please verify.

BTW, it's not a good idea to use CERMINE by executing it's unit tests, you should rather write a piece of code using CERMINE's classes, or execute `ContentExtractor` class through the JAR file.

**Comment by maxxkia** [comment]
Thanks it's fixed now.

Right, I know. I hit this error in version 1.13 and wanted to quickly test if I can reproduce it in the latest code so I added it to the unit test. Anyways the purpose of writing tests is to ensure the program is working as expected.
BTW, I think you added `test6.pdf` to the main resources by mistake.

**Comment by dtkaczyk** [comment]
Thanks, I moved the file to test resources.

You're right about the tests purpose, that's why I try to extend our test cases whenever a new bug is reported. However, unless you actually want to actively develop CERMINE, its main master branch or your own branch, it's better if you treated the system more as a black box, using it through the API. So for example, it might be a good idea for you to include unit tests testing CERMINE's performance, but not in our system, but in your own system that uses CERMINE. Of course these are just good practices, you have access to the code and you are welcomed to use it as you see fit :)

Since the issue reported in this thread is fixed, I'm closing it.
