### ISSUE TITLE
How can I avoid NaN exception: AtRelativeCount?

### ISSUE THREAD

**Issue by nvmnghia** [CeON/CERMINE#61]
I'm trying to train CERMINE again on an my university's scientific paper collection. However, after the InitialBuilder has iterated over all the files (~2300), it always throws this exception:

```
Exception in thread "main" java.lang.RuntimeException: Feature value is set to NaN: AtRelativeCount
	at pl.edu.icm.cermine.tools.classification.general.LinearScaling.scaleFeatureVector(LinearScaling.java:49)
	at pl.edu.icm.cermine.tools.classification.general.FeatureVectorScalerImpl.scaleFeatureVector(FeatureVectorScalerImpl.java:61)
	at pl.edu.icm.cermine.tools.classification.svm.SVMClassifier.buildDatasetForTraining(SVMClassifier.java:157)
	at pl.edu.icm.cermine.tools.classification.svm.SVMClassifier.buildClassifier(SVMClassifier.java:117)
	at pl.edu.icm.cermine.libsvm.training.SVMInitialBuilder.getZoneClassifier(SVMInitialBuilder.java:69)
	at pl.edu.icm.cermine.libsvm.training.SVMInitialBuilder.main(SVMInitialBuilder.java:143)

```
The line that causes the exception: 
`featureValue = a*featureValue + b;
`

Somehow the featureValue was NaN before the calculation. I think the issues may arise from my dataset. The cermstr dataset was generated from sidecars xml files in which all metadata are included: title, author, abstract, references,... I've proof read 20% of the files and everything seems normal. So far, the only problem I can think of is that there are too few examples of correspondence section, and this section usually spans only one line in a pdf file.
How should I improve my dataset to avoid this exception? Thanks!

**Comment by dtkaczyk** [comment]
@nvmnghia thanks for reporting.

Would you be able to locate the file that causes the error and share it with me? If not, can you share the collection (or a subset of it), so that I can reproduce this error?

Also, please provide the details about the version of CERMINE you are using and the exact command you are executing.

**Comment by dtkaczyk** [comment]
@nvmnghia  I am closing this issue for now, please reopen if you wish to investigate this further.
