### ISSUE TITLE
Handle invalid XML characters

### ISSUE THREAD

**Issue by eitanf** [CeON/CERMINE#66]
When converting to zones, some files (see [example](https://github.com/CeON/CERMINE/files/1515231/SIGMOD_17_015.pdf) fail with an exception from the JDOM parser:
`...
 is not legal for a JDOM character content: 0xdc98 is not a legal XML character.
	at org.jdom.Text.setText(Text.java:188)
	at org.jdom.Text.<init>(Text.java:99)
	at org.jdom.Element.addContent(Element.java:822)
	at pl.edu.icm.cermine.content.RawTextWithLabelsExtractor.addZone(RawTextWithLabelsExtractor.java:101)
	at pl.edu.icm.cermine.content.RawTextWithLabelsExtractor.extractRawTextWithLabels(RawTextWithLabelsExtractor.java:60)
	at pl.edu.icm.cermine.InternalContentExtractor.getLabelledFullText(InternalContentExtractor.java:258)
	at pl.edu.icm.cermine.ContentExtractor.getLabelledFullText(ContentExtractor.java:520)
	at pl.edu.icm.cermine.ContentExtractor.getLabelledFullText(ContentExtractor.java:535)
	at pl.edu.icm.cermine.ContentExtractor.main(ContentExtractor.java:835)
`

This is apparently caused by UTF-8 characters in the text that aren't legal in XML and need to be cleaned up (see [here](http://www.jdom.org/pipermail/jdom-interest/2002-July/010297.html)).

**Comment by eitanf** [comment]
A related issue is invalid surrogate pairs. If you try to extract zones from this [example](https://github.com/CeON/CERMINE/files/1519520/PODC_17_004.pdf)
, you'll get this error:

3.2" is not legal for a JDOM character content: Illegal Surrogate Pair.
	at org.jdom.Text.setText(Text.java:188)
	at org.jdom.Text.<init>(Text.java:99)
	at org.jdom.Element.addContent(Element.java:822)
	at pl.edu.icm.cermine.content.RawTextWithLabelsExtractor.addZone(RawTextWithLabelsExtractor.java:101)
	at pl.edu.icm.cermine.content.RawTextWithLabelsExtractor.extractRawTextWithLabels(RawTextWithLabelsExtractor.java:60)
	at pl.edu.icm.cermine.InternalContentExtractor.getLabelledFullText(InternalContentExtractor.java:258)
	at pl.edu.icm.cermine.ContentExtractor.getLabelledFullText(ContentExtractor.java:520)
	at pl.edu.icm.cermine.ContentExtractor.getLabelledFullText(ContentExtractor.java:535)
	at pl.edu.icm.cermine.ContentExtractor.main(ContentExtractor.java:835)


To fix this, we can translate invalid XML characters to their code points.

**Comment by dtkaczyk** [comment]
@eitanf thanks for reporting.

We already have a method for removing invalid XML chars (see `removeInvalidXMLChars` in https://github.com/CeON/CERMINE/blob/master/cermine-impl/src/main/java/pl/edu/icm/cermine/tools/XMLTools.java). I just verified that it is enough to add this additional cleaning to line 101 in https://github.com/CeON/CERMINE/blob/master/cermine-impl/src/main/java/pl/edu/icm/cermine/content/RawTextWithLabelsExtractor.java, and your example files get processed without problems. Feel free to change your pull request or create a new one for this.

Also, it seems to me our `removeInvalidXMLChars` does not handle surrogate pairs correctly. Feel free to fix this, but consider using `Verifier.isXMLCharacter` instead of enumerating invalid code points.

**Comment by eitanf** [comment]
I've updated the pull request with a much cleaner fix using XMLTools.removeInvalidXMLChars, as you've suggested. It seems to work on both files, so perhaps it does handle surrogate pairs correctly. Since I'm unable to reproduce a surrogate pairs problem, I suggest we pause here and incorporate this change.

**Comment by dtkaczyk** [comment]
Thanks, it's merged.
